version: '3.8'

services:
  app:
    image: mybackend
    build: .
    ports:
      - "8080:8080"
#    depends_on:
#      - postgres

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mydatabase
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password

#  postgres:
#    image: postgres:latest
#    environment:
#      POSTGRES_DB: mydatabase
#      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
#      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
#    ports:
#      - "5432:5432"